workflows:
  my-bookshelf-workflow:
    name: MyBookShelf
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: MyBook API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bookshelf.online
      vars:
        BUNDLE_ID: "com.bookshelf.online"
        XCODE_SCHEME: "MyBookShelf"
        APP_STORE_APPLE_ID: 6761006529
      xcode: latest
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd "$CM_BUILD_DIR"
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "MyBookShelf.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
